### ISSUE TITLE
Unable to build or run

### ISSUE THREAD

**Issue by ganeshchand** [knoldus/ScalaJs_Weather_Report#2]
I am getting java.lang.UnsupportedClassVersionError: com/typesafe/config/ConfigException : Unsupported major.minor version 52.0 when SBT RUN command is run in the terminal. Same error when I open the project in IntelliJ.

**Comment by satendrakumar06** [comment]
@ganeshchand  What java version are you using ?

**Comment by ganeshchand** [comment]
build 1.7.0_45-b18

**Comment by mevivs** [comment]
Seems like a case something is compiled with jdk < 1.7 and trying to run with jdk >=1.7

**Comment by ayushmishra2005** [comment]
@ganeshchand  Could you please try with Java 1.8?

**Comment by satendrakumar06** [comment]
[Play 2.5.x](https://github.com/playframework/playframework/blob/master/framework/project/Dependencies.scala) is coming with [typesafe Config library](https://github.com/typesafehub/config#supports-java-8-and-later) 1.3.0 version which Supports Java 8 and Later version.

@ganeshchand @mevivs

**Comment by mevivs** [comment]
@satendrakumar06  better to update README.MD for the same.

**Comment by satendrakumar06** [comment]
@mevivsThanks, Already created [pull request ](https://github.com/knoldus/ScalaJs_Weather_Report/pull/3)

**Comment by ayushmishra2005** [comment]
Thanks @satendrakumar06 . I have merged pull request.
